# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolate pitch points
#'
#' Given a vector of numeric timepoints `new_times` that lie within the range
#' of `old_times` and `pitch_vals` located at `old_times`, determine which
#' two pitch points are adjacent to each new timepoint, then calculate the
#' weighted mean based on how far the time point is from each pitch point to
#' interpolate between the two.
#'
#' @param new_times Sorted numeric vector with range within `old_times`
#' @param old_times Sorted numeric vector
#' @param pitch_vals Pitch values, of same length as `old_times`
#'
#' @return Numeric vector of interpolated pitch points to correspond to the
#' timepoints at `new_times`
interpolate_pitchpoints <- function(new_times, old_times, pitch_vals) {
    .Call(`_sosprosody_interpolate_pitchpoints`, new_times, old_times, pitch_vals)
}

