# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Make section indices
NULL

guess_interval_indices_string <- function(section_column) {
    .Call(`_sosprosody_guess_interval_indices_string`, section_column)
}

#' Make section indices
#'
#' Given a vector, assign contiguous groups based on where the values change.
#'
#' @param section_column Vector of values
#' @title Double section indices
#' @return Integer vector of indices for each contiguous group of values
guess_interval_indices_double <- function(section_column) {
    .Call(`_sosprosody_guess_interval_indices_double`, section_column)
}

#' Make section indices
NULL

guess_interval_indices_integer <- function(section_column) {
    .Call(`_sosprosody_guess_interval_indices_integer`, section_column)
}

#' Interpolate pitch points
NULL

interpolate_pitchpoints <- function(new_times, old_times, pitch_vals) {
    .Call(`_sosprosody_interpolate_pitchpoints`, new_times, old_times, pitch_vals)
}

